//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int ProdId { get; set; }
        public int EmpId { get; set; }
        public int CustId { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public string OrderDate { get; set; }
        public string ImageId { get; set; }
    }
}
