//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdId { get; set; }
        public string ProdName { get; set; }
        public string ProdCatageory { get; set; }
        public Nullable<int> ProdQuantity { get; set; }
        public Nullable<int> ProdPrice { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ImageID { get; set; }
    }
}
