//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopId { get; set; }
        public string ShopName { get; set; }
        public string ShopLocation { get; set; }
        public string ShopEmail { get; set; }
        public string ShopCategory { get; set; }
        public string UserId { get; set; }
    }
}
